name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            whoami
            ls -al
        #   script: |
        #     cd /home/ubuntu/frontend
        #     git pull
        #     # Assuming the built files are in the 'build' directory
        #     rsync -avz --delete ./dist/ /var/www/html/
        #     sudo systemctl restart nginx

#   build-and-test-application:
#     runs-on: ubuntu-latest

#     env:
#         PROJECT_DIR: "frontend"

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: npm install, build, and test
#         run: |
#           yarn install
#           yarn build
#           yarn test
#         working-directory: ${{ env.PROJECT_DIR }}

#       - name: Snyk code test and monitoring
#         run: |
#           snyk test $PROJECT_DIR
#           snyk monitor $PROJECT_DIR
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
